-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 01:51:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mindscapes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mindscapes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mindscapes` DEFAULT CHARACTER SET latin1 ;
USE `mindscapes` ;

-- -----------------------------------------------------
-- Table `mindscapes`.`domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`domain` (
  `iddomain` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iddomain`),
  UNIQUE INDEX `iddomain_UNIQUE` (`iddomain` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`course_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`course_type` (
  `idcourseType` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `idDomain` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idcourseType`),
  INDEX `domain_idx1` (`idDomain` ASC) VISIBLE,
  CONSTRAINT `domain`
    FOREIGN KEY (`idDomain`)
    REFERENCES `mindscapes`.`domain` (`iddomain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`employee_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`employee_role` (
  `idemployee_role` INT(10) UNSIGNED NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idemployee_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`location` (
  `idlocation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `locationName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlocation`),
  UNIQUE INDEX `idlocation_UNIQUE` (`idlocation` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mindscapes`.`Education_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`Education_Type` (
  `idEdType` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `EducationType_institution` VARCHAR(45) NOT NULL,
  `EductaionType_name` VARCHAR(45) NOT NULL,
  `location_idlocation` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEdType`),
  UNIQUE INDEX `idSchool_UNIQUE` (`idEdType` ASC) VISIBLE,
  INDEX `fk_school_location1_idx` (`location_idlocation` ASC) VISIBLE,
  CONSTRAINT `fk_school_location1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `mindscapes`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`education` (
  `ideducation` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `startDate` DATE NULL DEFAULT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  `Education_Type_idEdType` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ideducation`),
  INDEX `fk_education_Education_Type1_idx` (`Education_Type_idEdType` ASC) VISIBLE,
  CONSTRAINT `fk_education_Education_Type1`
    FOREIGN KEY (`Education_Type_idEdType`)
    REFERENCES `mindscapes`.`Education_Type` (`idEdType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`employee` (
  `idemployee` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `dateOfBirth` DATE NULL DEFAULT NULL,
  `role` INT(10) UNSIGNED NOT NULL,
  `experience` FLOAT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'working',
  `education_ideducation` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idemployee`),
  UNIQUE INDEX `idemployee_UNIQUE` (`idemployee` ASC) VISIBLE,
  INDEX `role_idx` (`role` ASC) VISIBLE,
  INDEX `fk_employee_education1_idx` (`education_ideducation` ASC) VISIBLE,
  CONSTRAINT `role`
    FOREIGN KEY (`role`)
    REFERENCES `mindscapes`.`employee_role` (`idemployee_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_education1`
    FOREIGN KEY (`education_ideducation`)
    REFERENCES `mindscapes`.`education` (`ideducation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`course` (
  `idcourse` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` INT(10) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `coordinator` INT(10) UNSIGNED NULL DEFAULT NULL,
  `startAge` INT NULL DEFAULT NULL,
  `endAge` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idcourse`),
  INDEX `coordiantor_idx` (`coordinator` ASC) VISIBLE,
  INDEX `type_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `type`
    FOREIGN KEY (`type`)
    REFERENCES `mindscapes`.`course_type` (`idcourseType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coordinator`
    FOREIGN KEY (`coordinator`)
    REFERENCES `mindscapes`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`semester` (
  `idsemester` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `semesterName` VARCHAR(45) NULL,
  `satrtDate` DATE NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`idsemester`),
  UNIQUE INDEX `idsemester_UNIQUE` (`idsemester` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mindscapes`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`section` (
  `idsection` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `instructor` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idCourse` INT(10) UNSIGNED NULL DEFAULT NULL,
  `room` VARCHAR(45) NULL DEFAULT NULL,
  `idSemester` INT UNSIGNED NULL,
  PRIMARY KEY (`idsection`),
  INDEX `instructor_idx` (`instructor` ASC) VISIBLE,
  INDEX `course_idx` (`idCourse` ASC) VISIBLE,
  INDEX `semester_idx` (`idSemester` ASC) VISIBLE,
  CONSTRAINT `idCourse`
    FOREIGN KEY (`idCourse`)
    REFERENCES `mindscapes`.`course` (`idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instructor`
    FOREIGN KEY (`instructor`)
    REFERENCES `mindscapes`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `semester`
    FOREIGN KEY (`idSemester`)
    REFERENCES `mindscapes`.`semester` (`idsemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`material` (
  `idmaterial` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(455) NULL DEFAULT NULL,
  `session_nb` INT(11) NULL DEFAULT NULL,
  `courseID` INT(10) UNSIGNED NULL DEFAULT NULL,
  `duration` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmaterial`),
  INDEX `course_idx` (`courseID` ASC) VISIBLE,
  CONSTRAINT `course`
    FOREIGN KEY (`courseID`)
    REFERENCES `mindscapes`.`course` (`idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`schedule` (
  `idschedule` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idSession` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idSection` INT(10) UNSIGNED NULL DEFAULT NULL,
  `time` VARCHAR(45) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  INDEX `session_idx` (`idSession` ASC) VISIBLE,
  INDEX `section_idx` (`idSection` ASC) VISIBLE,
  CONSTRAINT `idSection`
    FOREIGN KEY (`idSection`)
    REFERENCES `mindscapes`.`section` (`idsection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSession`
    FOREIGN KEY (`idSession`)
    REFERENCES `mindscapes`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`indicator_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`indicator_types` (
  `idindicator_types` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idindicator_types`),
  UNIQUE INDEX `idindicator_types_UNIQUE` (`idindicator_types` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`indicators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`indicators` (
  `idindicators` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` INT(10) UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idindicators`),
  UNIQUE INDEX `idindicators_UNIQUE` (`idindicators` ASC) VISIBLE,
  INDEX `type_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `typeInd`
    FOREIGN KEY (`type`)
    REFERENCES `mindscapes`.`indicator_types` (`idindicator_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`student` (
  `idStudent` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `studentFirstName` VARCHAR(45) NOT NULL,
  `studentLastName` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `phoneNb` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `education_ideducation` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `fk_student_education1_idx` (`education_ideducation` ASC) VISIBLE,
  CONSTRAINT `fk_student_education1`
    FOREIGN KEY (`education_ideducation`)
    REFERENCES `mindscapes`.`education` (`ideducation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`assessment` (
  `idassessment` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idStudent` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idSession` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idIndicator` INT(10) UNSIGNED NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `rate` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`idassessment`),
  UNIQUE INDEX `idassessment_UNIQUE` (`idassessment` ASC) VISIBLE,
  INDEX `studentss_idx` (`idStudent` ASC) VISIBLE,
  INDEX `sessionsss_idx` (`idSession` ASC) VISIBLE,
  INDEX `indicator_idx` (`idIndicator` ASC) VISIBLE,
  CONSTRAINT `indSessipon`
    FOREIGN KEY (`idSession`)
    REFERENCES `mindscapes`.`schedule` (`idschedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inds`
    FOREIGN KEY (`idIndicator`)
    REFERENCES `mindscapes`.`indicators` (`idindicators`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `indstuident`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mindscapes`.`student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`attendance` (
  `idattendance` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idStudent` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idSession` INT(10) UNSIGNED NULL DEFAULT NULL,
  `present` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idattendance`),
  INDEX `schedule_idx` (`idSession` ASC) VISIBLE,
  INDEX `student_idx` (`idStudent` ASC) VISIBLE,
  CONSTRAINT `session`
    FOREIGN KEY (`idSession`)
    REFERENCES `mindscapes`.`schedule` (`idschedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mindscapes`.`student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`legal_guardians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`legal_guardians` (
  `idLegalGuardians` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameLegalGuardians` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLegalGuardians`),
  UNIQUE INDEX `idContact_UNIQUE` (`idLegalGuardians` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`guardians_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`guardians_students` (
  `idguardians_students` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLegalGuardians` INT(10) UNSIGNED NULL DEFAULT NULL,
  `relationShip` VARCHAR(45) NULL DEFAULT NULL,
  `idStudent` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idguardians_students`),
  UNIQUE INDEX `idguardians_students_UNIQUE` (`idguardians_students` ASC) VISIBLE,
  INDEX `idLegalGuardian_idx` (`idLegalGuardians` ASC) VISIBLE,
  INDEX `idStudent_idx` (`idStudent` ASC) VISIBLE,
  CONSTRAINT `idStudent`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mindscapes`.`student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `legalGuardian`
    FOREIGN KEY (`idLegalGuardians`)
    REFERENCES `mindscapes`.`legal_guardians` (`idLegalGuardians`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`registration` (
  `idregistration` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idSection` INT(10) UNSIGNED NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'pending',
  `registrationDate` DATE NULL DEFAULT NULL,
  `fee` INT(11) NULL DEFAULT NULL,
  `idStudent` INT(10) UNSIGNED NULL DEFAULT NULL,
  `completionDate` DATE NULL,
  PRIMARY KEY (`idregistration`),
  INDEX `section_idx` (`idSection` ASC) VISIBLE,
  INDEX `idStudent_idx` (`idStudent` ASC) VISIBLE,
  CONSTRAINT `section`
    FOREIGN KEY (`idSection`)
    REFERENCES `mindscapes`.`section` (`idsection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sts`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mindscapes`.`student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`payment` (
  `idpayment` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` INT(11) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `idRegistration` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`idpayment`),
  INDEX `idRegistartion_idx` (`idRegistration` ASC) VISIBLE,
  CONSTRAINT `idRegistartion`
    FOREIGN KEY (`idRegistration`)
    REFERENCES `mindscapes`.`registration` (`idregistration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`salary` (
  `idSalary` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `IdEmployee` INT(10) UNSIGNED NOT NULL,
  `amount` DECIMAL NULL DEFAULT NULL,
  `currency` VARCHAR(45) NULL DEFAULT '$',
  PRIMARY KEY (`idSalary`),
  INDEX `employee_idx` (`IdEmployee` ASC) VISIBLE,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`IdEmployee`)
    REFERENCES `mindscapes`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mindscapes`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mindscapes`.`experience` (
  `idexperience` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idemployee` INT(10) UNSIGNED NULL,
  `description` VARCHAR(445) NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `companyName` VARCHAR(45) NULL,
  `companyAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`idexperience`),
  INDEX `idEmployeee_idx` (`idemployee` ASC) VISIBLE,
  CONSTRAINT `idEmployeee`
    FOREIGN KEY (`idemployee`)
    REFERENCES `mindscapes`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
